version: '3'

services:
  noginx:
    image: etzba/noginx:latest
    environment:
      - RELEASE_STAGE=testing
      - PORT=80
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
